### ISSUE TITLE
Cannot match images by filename

### ISSUE THREAD

**Issue by joeguilmette** [soflyy/wp-all-import-rapid-addon#24] opened 2019-01-21 06:49 UTC
When selecting to match images by their filename, the import template won't save the new setting.

Debug: http://exuberant-squirrel.w5.wpsandbox.pro/?upass=7S3rmGih12HT

https://github.com/soflyy/wpai-listify-add-on/issues/10

**Comment by mbissett** [comment] 2019-02-27 19:18
We had the reverse come up over here: https://github.com/soflyy/wp-all-import-rapid-addon/issues/24 - what's the status on this?

**Comment by cmdmcs** [comment] 2019-02-27 20:06
This is fixed in latest beta of WPAI - v4.5.6-beta-4.5 and master branch of Rapid Add-On.

**Comment by trey8611** [comment] 2019-02-28 16:40
@cmdmcs this is working in my tests. @mbissett can you test to confirm that it works for the reverse issue? I couldn't reproduce that.

@joeguilmette if all is good do you want me to push a new version of all add-ons with latest Rapid Add-On or should we wait until the WPAI Pro release?

**Comment by mbissett** [comment] 2019-03-02 22:44
@trey8611 I can confirm that this is fixed in my case as well. :)

**Comment by joeguilmette** [comment] 2019-03-18 11:54
> do you want me to push a new version of all add-ons with latest Rapid Add-On or should we wait until the WPAI Pro release

@trey8611 prepare all add-ons for release, and we'll release everything together with WPAI and WPAE and the user export add-on.

**Comment by trey8611** [comment] 2019-04-04 13:50
@cmdmcs I was testing this with Real Homes add-on and noticed that when I'm using the latest BETA or master branch of WP All Import Pro, neither option is selected by default when creating a new Properties import: https://d.pr/i/GESbBk. Replicated at:

http://ill-gerenuk.w5.wpsandbox.pro/?upass=5oA93ZuSOr6i

Server: w5.wpsandbox.pro
Port: 2222
Username: ill-gerenuk
Password: 6uBEJqVbYS5Y64s4zd91V8ru

**Comment by trey8611** [comment] 2019-04-04 13:54
@cmdmcs  Update: even if you select one of the options, it goes back to being deselected after running the import.

**Comment by trey8611** [comment] 2019-04-04 14:43
@cmdmcs you can disregard this it looks like I must have failed to copy the new rapid-addon file into the add-on lol I'm an idiot sorry.

**Comment by trey8611** [comment] 2019-04-04 19:25
@joeguilmette all free add-ons are ready for release. Let me know if I have the green light to push to wp.org.

**Closed** 2019-04-17 09:50 UTC
Labels: bug
